#!/usr/bin/env bash
# Show lines containing the word "bash" and extract the PID and process hierarchy

# shellcheck disable=SC2009
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm,args | grep "[b]ash"
