#!/usr/bin/env bash
#This will handle the sigterm

function handle_sigterm {
    echo "I am invincible!!!"
    exit 0
}

trap 'handle_sigterm' SIGTERM

i=1
while ((i))
do
    echo "To infinity and beyond"
    sleep 2
done
