#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file using the while loop and IFS

while IFS=: read -r username x userid groupid x x home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
