#!/usr/bin/env bash
# This script connects to the server using SSH with a private key

# Use the ssh command with the -i flag to specify the private key file.
# Replace 'server_ip' with the actual IP address of your server.
ssh -i ~/.ssh/school ubuntu@41.216.111.246
